### GET request to example server
GET http://localhost:8080

### GET software engineers
GET http://localhost:8080/api/v1/software-engineers

### POST new software engineer
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Jamila",
  "techStack": "Java Script, Node, React"
}

### GET a software engineer by id
GET http://localhost:8080/api/v1/software-engineers/1

### DELETE a software engineer by id
DELETE http://localhost:8080/api/v1/software-engineers/1

### PUT update a software engineer
PUT http://localhost:8080/api/v1/software-engineers/1
Content-Type: application/json

{
  "name": "John Doe",
  "techStack": "Java, Spring Boot, PostgreSQL"
}