### GET request to example server
GET http://localhost:8080

### GET software engineers
GET http://localhost:8080/api/v1/software-engineers

### Post new software engineer
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Jamila",
  "techStack": "Java Script, Node, React"
}
